openapi: 3.1.0
info:
  title: Mirror Node REST accounts airdrops API
  version: 0.156.0
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: 'The REST API offers the ability to query transactions and entity information from a mirror node.


    Base url: [/api/v1](/api/v1)


    OpenAPI Spec: [/api/v1/docs/openapi.yml](/api/v1/docs/openapi.yml)'
  contact:
    name: Mirror Node Team
    email: mirrornode@hedera.com
    url: https://github.com/hiero-ledger/hiero-mirror-node
servers:
- description: The current REST API server
  url: ''
- description: The production REST API servers
  url: '{scheme}://{network}.mirrornode.hedera.com'
  variables:
    scheme:
      default: https
      description: The URI scheme
      enum:
      - http
      - https
    network:
      default: testnet
      description: The Hedera network in use
      enum:
      - mainnet-public
      - mainnet
      - previewnet
      - testnet
tags:
- name: airdrops
paths:
  /api/v1/accounts/{idOrAliasOrEvmAddress}/airdrops/outstanding:
    get:
      summary: Get outstanding token airdrops sent by an account
      description: 'Returns outstanding token airdrops that have been sent by an account.

        '
      operationId: getOutstandingTokenAirdrops
      parameters:
      - $ref: '#/components/parameters/accountIdOrAliasOrEvmAddressPathParam'
      - $ref: '#/components/parameters/limitQueryParam'
      - $ref: '#/components/parameters/orderQueryParam'
      - $ref: '#/components/parameters/receiverIdQueryParam'
      - $ref: '#/components/parameters/serialNumberQueryParam'
      - $ref: '#/components/parameters/tokenIdQueryParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenAirdropsResponse'
        '400':
          $ref: '#/components/responses/InvalidParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      tags:
      - airdrops
  /api/v1/accounts/{idOrAliasOrEvmAddress}/airdrops/pending:
    get:
      summary: Get pending token airdrops received by an account
      description: 'Returns pending token airdrops that have been received by an account.

        '
      operationId: getPendingTokenAirdrops
      parameters:
      - $ref: '#/components/parameters/accountIdOrAliasOrEvmAddressPathParam'
      - $ref: '#/components/parameters/limitQueryParam'
      - $ref: '#/components/parameters/orderQueryParam'
      - $ref: '#/components/parameters/senderIdQueryParam'
      - $ref: '#/components/parameters/serialNumberQueryParam'
      - $ref: '#/components/parameters/tokenIdQueryParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenAirdropsResponse'
        '400':
          $ref: '#/components/responses/InvalidParameterError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      tags:
      - airdrops
components:
  responses:
    InvalidParameterError:
      description: Invalid parameter
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            _status:
              messages:
              - message: 'Invalid parameter: account.id'
              - message: Invalid Transaction id. Please use \shard.realm.num-sss-nnn\ format where sss are seconds and nnn are nanoseconds
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            _status:
              messages:
              - message: Not found
  parameters:
    receiverIdQueryParam:
      name: receiver.id
      description: The ID of the receiver to return information for
      in: query
      examples:
        noValue:
          summary: --
          value: ''
        entityNumNoOperator:
          summary: Example of entityNum equals with no operator
          value: 100
        idNoOperator:
          summary: Example of id equals with no operator
          value: 0.0.100
        entityNumEqOperator:
          summary: Example of entityNum equals operator
          value: eq:200
        idEqOperator:
          summary: Example of id equals operator
          value: eq:0.0.200
        idGtOperator:
          summary: Example of id greather than operator
          value: gt:0.0.200
        idGteOperator:
          summary: Example of id greather than or equal to operator
          value: gte:0.0.200
        idLtOperator:
          summary: Example of id less than operator
          value: lt:0.0.200
        idLteOperator:
          summary: Example of id less than or equal to operator
          value: lte:0.0.200
      schema:
        $ref: '#/components/schemas/EntityIdQuery'
    serialNumberQueryParam:
      name: serialnumber
      in: query
      explode: true
      description: The nft serial number (64 bit type). Requires a tokenId value also be populated.
      examples:
        noValue:
          summary: --
          value: ''
        serialNumNoOperator:
          summary: Example of serialNum equals with no operator
          value: 100
        serialNumEqOperator:
          summary: Example of serialNum equals operator
          value: eq:200
        serialNumGtOperator:
          summary: Example of serialNum greater than operator
          value: gt:400
        serialNumGteOperator:
          summary: Example of serialNum greater than or equals operator
          value: gte:500
        serialNumLtOperator:
          summary: Example of serialNum less than operator
          value: lt:600
        serialNumLteOperator:
          summary: Example of serialNum less than or equals operator
          value: lte:700
      schema:
        type: string
        pattern: ^((eq|gt|gte|lt|lte):)?\d{1,19}?$
    orderQueryParam:
      name: order
      in: query
      description: The order in which items are listed
      example: desc
      schema:
        enum:
        - asc
        - desc
        default: asc
    accountIdOrAliasOrEvmAddressPathParam:
      name: idOrAliasOrEvmAddress
      in: path
      description: Account alias or account id or evm address
      required: true
      examples:
        aliasOnly:
          value: HIQQEXWKW53RKN4W6XXC4Q232SYNZ3SZANVZZSUME5B5PRGXL663UAQA
        realmAlias:
          value: 0.HIQQEXWKW53RKN4W6XXC4Q232SYNZ3SZANVZZSUME5B5PRGXL663UAQA
        shardRealmAlias:
          value: 0.1.HIQQEXWKW53RKN4W6XXC4Q232SYNZ3SZANVZZSUME5B5PRGXL663UAQA
        accountNumOnly:
          value: 8
        realmAccountNum:
          value: 0.8
        shardRealmAccountNum:
          value: 0.0.8
        evmAddress:
          value: ac384c53f03855fa1b3616052f8ba32c6c2a2fec
        evmAddressWithPrefix:
          value: 9.832019034092927e+47
        evmAddressWithShardAndRealm:
          value: 0.0.ac384c53f03855fa1b3616052f8ba32c6c2a2fec
      schema:
        pattern: ^(\d{1,10}\.){0,2}(\d{1,10}|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))$
        type: string
    limitQueryParam:
      name: limit
      in: query
      description: The maximum number of items to return
      example: 2
      schema:
        format: int32
        type: integer
        default: 25
        minimum: 1
        maximum: 100
    senderIdQueryParam:
      name: sender.id
      description: The ID of the sender to return information for
      in: query
      examples:
        noValue:
          summary: --
          value: ''
        entityNumNoOperator:
          summary: Example of entityNum equals with no operator
          value: 100
        idNoOperator:
          summary: Example of id equals with no operator
          value: 0.0.100
        entityNumEqOperator:
          summary: Example of entityNum equals operator
          value: eq:200
        idEqOperator:
          summary: Example of id equals operator
          value: eq:0.0.200
        idGtOperator:
          summary: Example of id greather than operator
          value: gt:0.0.200
        idGteOperator:
          summary: Example of id greather than or equal to operator
          value: gte:0.0.200
        idLtOperator:
          summary: Example of id less than operator
          value: lt:0.0.200
        idLteOperator:
          summary: Example of id less than or equal to operator
          value: lte:0.0.200
      schema:
        $ref: '#/components/schemas/EntityIdQuery'
    tokenIdQueryParam:
      name: token.id
      description: The ID of the token to return information for
      in: query
      examples:
        noValue:
          summary: --
          value: ''
        tokenNumAlias:
          summary: Example of token num alias equals with no operator
          value: 64
        entityNumNoOperator:
          summary: Example of entityNum equals with no operator
          value: 100
        idNoOperator:
          summary: Example of id equals with no operator
          value: 0.0.100
        entityNumEqOperator:
          summary: Example of entityNum equals operator
          value: eq:200
        idEqOperator:
          summary: Example of id equals operator
          value: eq:0.0.200
        entityNumNeOperator:
          summary: Example of entityNum not equals operator
          value: ne:300
        idNeOperator:
          summary: Example of id not equals operator
          value: ne:0.0.300
        entityNumGtOperator:
          summary: Example of entityNum greater than operator
          value: gt:400
        idGtOperator:
          summary: Example of id greater than operator
          value: gt:0.0.400
        entityNumGteOperator:
          summary: Example of entityNum greater than or equals operator
          value: gte:500
        idGteOperator:
          summary: Example of id greater than or equals operator
          value: gte:0.0.500
        entityNumLtOperator:
          summary: Example of entityNum less than operator
          value: lt:600
        idLtOperator:
          summary: Example of id less than operator
          value: lt:0.0.600
        entityNumLteOperator:
          summary: Example of entityNum less than or equals operator
          value: lte:700
        idLteOperator:
          summary: Example of id less than or equals operator
          value: lte:0.0.700
      schema:
        $ref: '#/components/schemas/EntityIdQuery'
  schemas:
    EntityIdQuery:
      type: string
      pattern: ^((gte?|lte?|eq|ne)\:)?(\d{1,10}\.\d{1,10}\.)?\d{1,10}$
    TimestampRange:
      type: object
      description: A timestamp range an entity is valid for
      properties:
        from:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The inclusive from timestamp in seconds
        to:
          allOf:
          - $ref: '#/components/schemas/TimestampNullable'
          - description: The exclusive to timestamp in seconds
    TimestampNullable:
      description: A Unix timestamp in seconds.nanoseconds format
      type:
      - string
      - 'null'
      example: '1586567700.453054000'
      pattern: ^\d{1,10}(\.\d{1,9})?$
    TokenAirdrop:
      type: object
      properties:
        amount:
          format: int64
          type: integer
        receiver_id:
          $ref: '#/components/schemas/EntityId'
        sender_id:
          $ref: '#/components/schemas/EntityId'
        serial_number:
          example: 1
          format: int64
          type:
          - integer
          - 'null'
        timestamp:
          $ref: '#/components/schemas/TimestampRange'
        token_id:
          $ref: '#/components/schemas/EntityId'
      example:
        amount: 10
        receiver_id: 0.0.15
        sender_id: 0.0.10
        serial_number: null
        timestamp:
          from: '1651560386.060890949'
          to: '1651560386.661997287'
        token_id: 0.0.99
      required:
      - amount
      - receiver_id
      - sender_id
      - timestamp
      - token_id
    TokenAirdropsResponse:
      type: object
      properties:
        airdrops:
          $ref: '#/components/schemas/TokenAirdrops'
        links:
          $ref: '#/components/schemas/Links'
    Links:
      type: object
      properties:
        next:
          example: null
          type:
          - string
          - 'null'
    EntityId:
      type:
      - string
      - 'null'
      description: Network entity ID in the format of `shard.realm.num`
      pattern: ^\d{1,10}\.\d{1,10}\.\d{1,10}$
      example: 0.0.2
    Timestamp:
      description: A Unix timestamp in seconds.nanoseconds format
      type: string
      example: '1586567700.453054000'
      pattern: ^\d{1,10}(\.\d{1,9})?$
    Error:
      type: object
      properties:
        _status:
          type: object
          properties:
            messages:
              type: array
              items:
                type: object
                properties:
                  data:
                    description: Error message in hexadecimal
                    example: '0x3000'
                    format: binary
                    pattern: ^0x[0-9a-fA-F]+$
                    type:
                    - string
                    - 'null'
                  detail:
                    description: Detailed error message
                    example: Generic detailed error message
                    type:
                    - string
                    - 'null'
                  message:
                    description: Error message
                    example: Generic error message
                    type: string
    TokenAirdrops:
      type: array
      items:
        $ref: '#/components/schemas/TokenAirdrop'
externalDocs:
  description: REST API Docs
  url: https://docs.hedera.com/guides/docs/mirror-node-api/cryptocurrency-api
